[package]
name = "boxx"
description = "Display informational boxes in the terminal."
version = "0.0.1-alpha"
repository = "https://github.com/EverlastingBugstopper/boxx"
authors = ["Avery Harnish <averyharnish@gmail.com>"]
categories = ["value-formatting"]
keywords = ["boxx", "cli", "terminal", "boxen", "info"]
readme = "README.md"
edition = "2018"
license = "MIT/Apache-2.0"

[[example]]
name = "alignment"
path = "examples/alignment.rs"

[[example]]
name = "color"
path = "examples/color.rs"

[[example]]
name = "custom"
path = "examples/custom.rs"

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[dependencies]
console = "0.9"
term_size = "0.3"
unicode-width = "0.1"

[dev-dependencies]
version-sync = "0.8"